sequenceDiagram
  participant scenario
  box web
    participant http
  end
  box installations
    participant InstallationService
    participant InstallationReadModel
    participant scenario
  end
  box communication
    participant KnownDevicesReadModel
  end
  box mediators
  end
  box device
    participant DeviceService
  end
  box search
    participant DevicesReadModel
  end
  box persistence
    participant Repository
  end
  scenario ->>+ InstallationService: handleWorkOrder
  InstallationService ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationEventSourcingRepository$InstallationEventEntity
  Repository ->> Repository: SELECT installation_events
  Repository ->>- InstallationService: return save
  InstallationService ->>+ InstallationReadModel: projectionOf
  InstallationReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return findById
  InstallationReadModel ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return save
  InstallationReadModel ->>- InstallationService: return projectionOf
  InstallationService ->>- scenario: return handleWorkOrder
  scenario ->>+ Repository: Transaction.commit
  Repository ->> Repository: INSERT installation_events
  Repository ->> Repository: INSERT installation
  Repository ->>- scenario: return Transaction.commit
  scenario ->>+ http: GET
  http ->> http: GET /installations
  http ->> http: GET
  http ->> http: GET
  http ->>+ Repository: test
  Repository ->>- http: return test
  http ->>+ InstallationReadModel: query
  InstallationReadModel ->>+ Repository: findAllMatching
  Repository ->> Repository: SELECT installation
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return findAllMatching
  InstallationReadModel ->>- http: return query
  http ->>+ Repository: Transaction.commit
  Repository ->>- http: return Transaction.commit
  http ->>- scenario: return GET
  scenario ->>+ http: GET
  http ->> http: GET /installations/{orderId}
  http ->>+ InstallationReadModel: queryByOrderId
  InstallationReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return findById
  InstallationReadModel ->>- http: return queryByOrderId
  http ->>+ Repository: Transaction.commit
  Repository ->>- http: return Transaction.commit
  http ->>- scenario: return GET
  scenario ->>+ http: PATCH
  http ->> http: PATCH /installations/{orderId}
  http ->>+ InstallationService: assignDevice
  InstallationService ->>+ Repository: findByOrderId
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: SELECT installation_events
  Repository ->>- InstallationService: return findByOrderId
  InstallationService ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationEventSourcingRepository$InstallationEventEntity
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: Transaction.commit
  Repository ->> Repository: INSERT installation_events
  Repository ->>- InstallationService: return save
  InstallationService ->>+ KnownDevicesReadModel: projectionOfDeviceInstallation
  KnownDevicesReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.communication.KnownDevicesReadModel$KnownDeviceEntity
  Repository ->> Repository: SELECT known_device
  Repository ->>- KnownDevicesReadModel: return findById
  KnownDevicesReadModel ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.communication.KnownDevicesReadModel$KnownDeviceEntity
  Repository ->> Repository: SELECT known_device
  Repository ->>- KnownDevicesReadModel: return save
  KnownDevicesReadModel ->>- InstallationService: return projectionOfDeviceInstallation
  InstallationService ->>+ Repository: Transaction.commit
  Repository ->> Repository: INSERT known_device
  Repository ->>- InstallationService: return Transaction.commit
  InstallationService ->>+ InstallationReadModel: projectionOf
  InstallationReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return findById
  InstallationReadModel ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->>- InstallationReadModel: return save
  InstallationReadModel ->>- InstallationService: return projectionOf
  InstallationService ->>+ Repository: Transaction.commit
  Repository ->> Repository: UPDATE installation
  Repository ->>- InstallationService: return Transaction.commit
  InstallationService ->>- http: return assignDevice
  http ->>+ Repository: findByOrderId
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: SELECT installation_events
  Repository ->>- http: return findByOrderId
  http ->>- scenario: return PATCH
  scenario ->>+ http: PATCH
  http ->> http: PATCH /installations/{orderId}
  http ->>+ InstallationService: assignLocation
  InstallationService ->>+ Repository: findByOrderId
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: SELECT installation_events
  Repository ->>- InstallationService: return findByOrderId
  InstallationService ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationEventSourcingRepository$InstallationEventEntity
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: Transaction.commit
  Repository ->> Repository: INSERT installation_events
  Repository ->>- InstallationService: return save
  InstallationService ->>+ InstallationReadModel: projectionOf
  InstallationReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return findById
  InstallationReadModel ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->>- InstallationReadModel: return save
  InstallationReadModel ->>- InstallationService: return projectionOf
  InstallationService ->>+ Repository: Transaction.commit
  Repository ->>- InstallationService: return Transaction.commit
  InstallationService ->>- http: return assignLocation
  http ->>+ Repository: findByOrderId
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: SELECT installation_events
  Repository ->>- http: return findByOrderId
  http ->>- scenario: return PATCH
  scenario ->>+ InstallationService: handleBootNotification
  InstallationService ->>+ Repository: findByDeviceId
  Repository ->> Repository: SELECT
  Repository ->> Repository: SELECT
  Repository ->>- InstallationService: return findByDeviceId
  InstallationService ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationEventSourcingRepository$InstallationEventEntity
  Repository ->> Repository: SELECT installation_events
  Repository ->>- InstallationService: return save
  InstallationService ->>+ InstallationReadModel: projectionOf
  InstallationReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return findById
  InstallationReadModel ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->>- InstallationReadModel: return save
  InstallationReadModel ->>- InstallationService: return projectionOf
  InstallationService ->>- scenario: return handleBootNotification
  scenario ->>+ Repository: Transaction.commit
  Repository ->> Repository: INSERT installation_events
  Repository ->> Repository: UPDATE installation
  Repository ->>- scenario: return Transaction.commit
  scenario ->>+ http: GET
  http ->> http: GET /installations/{orderId}
  http ->>+ InstallationReadModel: queryByOrderId
  InstallationReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return findById
  InstallationReadModel ->>- http: return queryByOrderId
  http ->>+ Repository: Transaction.commit
  Repository ->>- http: return Transaction.commit
  http ->>- scenario: return GET
  scenario ->>+ http: PATCH
  http ->> http: PATCH /installations/{orderId}
  http ->>+ InstallationService: confirmBootData
  InstallationService ->>+ Repository: findByOrderId
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: SELECT installation_events
  Repository ->>- InstallationService: return findByOrderId
  InstallationService ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationEventSourcingRepository$InstallationEventEntity
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: Transaction.commit
  Repository ->> Repository: INSERT installation_events
  Repository ->>- InstallationService: return save
  InstallationService ->>+ InstallationReadModel: projectionOf
  InstallationReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return findById
  InstallationReadModel ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->>- InstallationReadModel: return save
  InstallationReadModel ->>- InstallationService: return projectionOf
  InstallationService ->>+ Repository: Transaction.commit
  Repository ->>- InstallationService: return Transaction.commit
  InstallationService ->>- http: return confirmBootData
  http ->>+ Repository: findByOrderId
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: SELECT installation_events
  Repository ->>- http: return findByOrderId
  http ->>- scenario: return PATCH
  scenario ->>+ http: PATCH
  http ->> http: PATCH /installations/{orderId}
  http ->>+ InstallationService: complete
  InstallationService ->>+ Repository: findByOrderId
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: SELECT installation_events
  Repository ->>- InstallationService: return findByOrderId
  InstallationService ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationEventSourcingRepository$InstallationEventEntity
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: Transaction.commit
  Repository ->> Repository: INSERT installation_events
  Repository ->>- InstallationService: return save
  InstallationService ->>+ KnownDevicesReadModel: projectionOfInstallationCompleted
  KnownDevicesReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.communication.KnownDevicesReadModel$KnownDeviceEntity
  Repository ->> Repository: SELECT known_device
  Repository ->>- KnownDevicesReadModel: return findById
  KnownDevicesReadModel ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.communication.KnownDevicesReadModel$KnownDeviceEntity
  Repository ->>- KnownDevicesReadModel: return save
  KnownDevicesReadModel ->>- InstallationService: return projectionOfInstallationCompleted
  InstallationService ->>+ Repository: Transaction.commit
  Repository ->> Repository: UPDATE known_device
  Repository ->>- InstallationService: return Transaction.commit
  InstallationService ->>+ InstallationReadModel: projectionOf
  InstallationReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->> Repository: SELECT installation
  Repository ->>- InstallationReadModel: return findById
  InstallationReadModel ->>+ Repository: save
  Repository ->> Repository: Session.merge devices.configuration.installations.InstallationReadModel$InstallationEntity
  Repository ->>- InstallationReadModel: return save
  InstallationReadModel ->>- InstallationService: return projectionOf
  InstallationService ->>+ Repository: Transaction.commit
  Repository ->> Repository: UPDATE installation
  Repository ->>- InstallationService: return Transaction.commit
  InstallationService ->>+ DeviceService: createNewDevice
  DeviceService ->>+ Repository: save
  Repository ->> Repository: findById
  Repository ->> Repository: Session.find devices.configuration.device.DeviceDocumentWithHistoryRepository$DeviceDocumentEntity
  Repository ->> Repository: SELECT device_document
  Repository ->> Repository: save
  Repository ->> Repository: Session.merge devices.configuration.device.DeviceDocumentWithHistoryRepository$DeviceDocumentEntity
  Repository ->> Repository: SELECT device_document
  Repository ->> Repository: save
  Repository ->> Repository: Session.merge devices.configuration.device.DeviceDocumentWithHistoryRepository$DeviceEventEntity
  Repository ->> Repository: SELECT device_events
  Repository ->> Repository: save
  Repository ->> Repository: Session.merge devices.configuration.device.DeviceDocumentWithHistoryRepository$DeviceEventEntity
  Repository ->> Repository: SELECT device_events
  Repository ->>+ KnownDevicesReadModel: projectionOfDeInstallation
  KnownDevicesReadModel ->>- Repository: return projectionOfDeInstallation
  Repository ->>+ DevicesReadModel: projectionOf
  DevicesReadModel ->>+ Repository: findById
  Repository ->> Repository: Session.find devices.configuration.search.DevicesReadModel$DeviceReadsEntity
  Repository ->> Repository: SELECT search
  Repository ->>- DevicesReadModel: return findById
  DevicesReadModel ->>+ Repository: save
  Repository ->> Repository: Session.persist devices.configuration.search.DevicesReadModel$DeviceReadsEntity
  Repository ->>- DevicesReadModel: return save
  DevicesReadModel ->>- Repository: return projectionOf
  Repository ->>- DeviceService: return save
  DeviceService ->>- InstallationService: return createNewDevice
  InstallationService ->>+ Repository: Transaction.commit
  Repository ->> Repository: INSERT device_document
  Repository ->> Repository: INSERT device_events
  Repository ->> Repository: INSERT device_events
  Repository ->> Repository: INSERT search
  Repository ->>- InstallationService: return Transaction.commit
  InstallationService ->>- http: return complete
  http ->>+ Repository: findByOrderId
  Repository ->> Repository: SELECT installation_events
  Repository ->> Repository: SELECT installation_events
  Repository ->>- http: return findByOrderId
  http ->>- scenario: return PATCH
